DATA_DIR = "dataset"
BATCH_SIZE = 4
IMAGE_WIDTH = int(245/2) 
IMAGE_HEIGHT = int(125/2)
NUM_WORKERS = 1
EPOCHS = 100
DEVICE = "cuda"

VIEW_INFERENCE_WHILE_TRAINING = True
SAVE_CHECKPOINTS = False
SAVE_MODEL_AS = "./model.pth"