DATA_DIR = "dataset/"
BATCH_SIZE = 8
IMAGE_WIDTH = 70 
IMAGE_HEIGHT = 25
NUM_WORKERS = 4
EPOCHS = 25
DEVICE = "cuda"

VIEW_INFERENCE_WHILE_TRAINING = False
SAVE_CHECKPOINTS = False
SAVE_MODEL_AS = "./your_model_name.pth"